### ISSUE TITLE
Lettuce偶现Connection reset by peer

### ISSUE THREAD

**Issue by quan7u** [quan7u/blog#2]
最近上线一个后台管理系统的服务组件，老是收到投诉说验证码、登录报错了，一直请求没反应，于是查看该组件的监控情况
![image](https://github.com/quan7u/blog/assets/32817309/518f28e8-8aa0-4228-937f-548e10e2a749)
可以看到这个组件的访问频率很低，每次超时情况的接口耗时在20s左右

监控也显示接口异常，先定位错误日志的堆栈信息
```java
org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: io.netty.channel.unix.Errors$NativeIoExc
eption: readAddress(..) failed: Connection reset by peer
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74)
        at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41)
        at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44)
        at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42)
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:272)
        at org.springframework.data.redis.connection.lettuce.LettuceConnection.await(LettuceConnection.java:1063)
```

出现了最有用的信息，也是标题，这个错误指的是TCP连接中，对端发送了RST信号，中断连接。
https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean
这篇最高赞的回答很有意思
_"Connection reset by peer" is the TCP/IP equivalent of slamming the phone back on the hook. It's more polite than merely not replying, leaving one hanging. But it's not the FIN-ACK expected of the truly polite TCP/IP converseur._

由于是TCP连接被中断了，可以猜到要么是连接池配置的有问题，要么是redis服务配置的连接超时时间太短了
先看redis客户端连接池配置，我们使用的是lettuce
```yaml
spring:
  redis:
    lettuce:
      pool:
        # 连接池最大连接数默认值为8
        max-active: 100
        # 连接池最大阻塞时间（使用负值表示没有限制）默认值为-1
        max-wait: -1
        # 连接池中最大空闲连接数默认值为8
        max-idle: 10
        # 连接池中的最小空闲连接数，默认值为0
        min-idle: 10
```
其实到这里，我也没怀疑是连接池配置的问题，因为中间件相关的配置我们是公用的，如果连接池有问题，那么其它的服务组件也会存在类似的问题（目前只有这个管理后台的接口组件有问题

检查下redis的配置
![image](https://github.com/quan7u/blog/assets/32817309/53ed154d-5b4a-4145-9b63-a12a1a54233d)
timeout配置是360秒，不敢乱改。。（这个不知道是不是运维同事配置的，默认应该是0）

既然连接池最小空闲也没问题，难道重新连接失败了？这里我去看了下组件的日志，lettuce超时reconnected都成功的，间隔时间也是比较正常的。
这就奇怪了，一直在网上搜相关问题，终于看到一篇提到lettuce连接池的影响 https://www.dazhuanlan.com/panyupei/topics/1215150
`org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory`的文档注释上提到
_This factory creates a new LettuceConnection on each call to getConnection(). Multiple LettuceConnections share a single thread-safe native connection by default.
The shared native connection is never closed by LettuceConnection, **therefore it is not validated by default on getConnection().** Use setValidateConnection(boolean) to change this behavior if necessary. Inject a Pool to pool dedicated connections. If shareNativeConnection is true, the pool will be used to select a connection for blocking and tx operations only, which should not share a connection. If native connection sharing is disabled, the selected connection will be used for all operations._

**关键**：默认情况下，获取连接不会去检查连接的状态

问题应该就是出在这里了，连接池配置是没有问题的，redis server的超时时间触发RST给到长时间空闲的连接，导致连接池的连接已经被关闭了，组件再次收到请求时，在连接池获取连接执行命令才暴露错误。

照着文档的说明，只需要配置工厂为`setValidateConnection(boolean)`即可，这样每次获取连接会去校验，如果校验连接失效会创建连接。

**~至此问题定位解决~**，一直听说lettuce有很多坑，这个应该也属于是比较常见的问题，顺手记录下。

**Comment by 3Flos** [comment]
goooooooooooooooooood
