### ISSUE TITLE
Lettuce超时问题Command timed out after xxx

### ISSUE THREAD

**Issue by quan7u** [quan7u/blog#3]
## 前言
接上文 [[Lettuce偶现Connection reset by peer](https://github.com/quan7u/blog/issues/2)](https://github.com/quan7u/blog/issues/2)
问题并没有解决，衍生出`io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 second(s)`的问题
挖个坑，后续再写。。

异常中after **x** second(s)，这个x源于组件的连接配置，默认应该是10s

## 复现
此问题与 https://github.com/lettuce-io/lettuce-core/issues/2082 是同一个问题，参照原po主的复现步骤即可复现

1、iptables屏蔽redis端口流入、流出的数据包
```shell
iptables -A INPUT -p tcp --dport 6377 -j DROP
iptables -A OUTPUT -p tcp --sport 6377 -j DROP
```

2、~~等待15分钟（926.4s）~~「注意这个时间」

3、客户端操作redis，异常信息以及Wireshark抓包记录如下
```java
io.lettuce.core.RedisCommandTimeoutException: Command timed out after 10 second(s)
    at io.lettuce.core.internal.ExceptionFactory.createTimeoutException(ExceptionFactory.java:59)
    at io.lettuce.core.internal.Futures.awaitOrCancel(Futures.java:246)
    at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:74)
    at org.springframework.data.redis.connection.lettuce.LettuceConnection.await(LettuceConnection.java:1061)
    at org.springframework.data.redis.connection.lettuce.LettuceConnection.lambda$doInvoke$4(LettuceConnection.java:920)
    at org.springframework.data.redis.connection.lettuce.LettuceInvoker$Synchronizer.invoke(LettuceInvoker.java:665)
    at org.springframework.data.redis.connection.lettuce.LettuceInvoker.just(LettuceInvoker.java:94)
    at org.springframework.data.redis.connection.lettuce.LettuceStringCommands.get(LettuceStringCommands.java:55)
    at org.springframework.data.redis.connection.DefaultedRedisConnection.get(DefaultedRedisConnection.java:278)
    at org.springframework.data.redis.connection.DefaultStringRedisConnection.get(DefaultStringRedisConnection.java:419)
    at org.springframework.data.redis.core.DefaultValueOperations$1.inRedis(DefaultValueOperations.java:58)
    at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:61)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:223)
    at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:190)
    at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
    at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:54)
......

```
![图片](https://github.com/quan7u/blog/assets/32817309/df5a7669-ab0d-4af7-b2f6-cd75b71c89d2)

## 分析
看抓包结果，可以发现经过n次重传（Retransmission）之后，客户端发出RST**断开连接**

> 这里和常见的15次（tcp_retries2）、924.6s对应不上，因为我是在Windows上复现的，随便搜了一下没看到Windows的相关配置，先暂时忽略吧。只要知道「网络出现分区后，用已存在的连接第一次请求操作redis，lettuce客户端会抛出异常并断开连接」即可！

**「网络出现分区后，用已存在的连接第一次请求操作redis，lettuce客户端会抛出异常并断开连接」**

这是一个简单又很困扰的问题。在原po与lettuce作者的讨论中，
- 原po（业务角度，没错，我也是业务）觉得既然客户端发现该连接tcp已经失效了，应该重连，重连成功后，继续请求返回正确的数据。
- 作者（应该属于中间件角度）认为网络分区就该解决分区的问题；连接失效就应该抛出异常。。。（我觉得也挺合理的）
后续原po大神提了个pr（通过定时去ping redis server，重连那些失效的连接），被作者拒绝了（连接应该以keepalive的机制去确保活跃，也是不破坏redis的相关协议）

其实看到这里，可能很多人认为lettuce没有重连机制？（以及网上大部分博客，在这个问题上拿jedis和lettuce做对比，都说lettuce没有重连机制）

**其实不然，在第一次请求多次tcp重传发现tcp连接失效，抛出异常给调用方之后，会进行重连！**
![图片](https://github.com/quan7u/blog/assets/32817309/939143c9-681c-463d-ab0d-82b41ab39497)

这也是当初我们遇到这个问题，将它归结为“玄学”的原因。
背景是一个客服系统，长时间不使用后redis连接会失效（我严重怀疑是虚拟主机或者waf之类的机制会定期清除没有数据传输的长连接）
晚上没有人使用，redis连接逐渐都失效了，第二天客服上班登录该系统，会出现上面的Command timed out after 10 second(s)异常。
又由于是连接池，客服第一次请求用的连接失败重连后具备使用后，再点击按钮可能又用了池子里别的失效连接。
等客服投诉到我们开发这边的时候，池子里的连接基本重连恢复了，而且白天工作时间，操作较为频繁，线上又无法复现问题了。

### 一、定时ping（❌
同事在网上找了个定时ping redis的定时任务，发版后还是没有解决问题。（我怀疑一个是连接池的问题，定时任务没有将所有的连接都保活；还有就是定时ping的时间>重传的时间，连接还是不定期失效，没有根本解决问题）

### 二、获取连接时验证连接（❌
我还发现lettuce连接工厂有一个验证连接的方法
> org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory#setValidateConnection

这也是个坑，每次获取连接都要加锁检验，同步改完发版后，导致高并发的组件线程数飙升，全阻塞在这获取连接了。。

### 三、tcp_user_timeout（✅
在https://github.com/lettuce-io/lettuce-core/issues/2082的讨论中，有个大佬提出
配置 keep-alive 和 tcp_user_timeout 可以解决问题，原po也验证过在Linux下确实能够解决问题。
（个人更加看好这个方案）

### 四、替换Jedis（✅
替换为Jedis，这也是我们选择的方案。作为经过业务校验的客户端库，jedis无非是最好的选择，直接替换依赖即可。
没有使用方案三解决，更多是因为这个问题长时间没有定位并得到解决，偶现的分区（或者可能是waf机制长连接清理）无法溯源，权限有限，依赖于客户那边的云主机（不太配合排查。。

## 小结
完全理想的情况下，建议使用Lettuce

当存在网络不理想、主从切换？等等情况，建议还是使用Jedis，对于错误连接的检测和重连更加积极（有各种策略主动去探测连接的情况，剔除无效的连接，避免业务报错）

做过复现步骤的朋友别忘记恢复iptables......
```shell
iptables -F INPUT
iptables -F OUTPUT
```

### 参考资料
https://www.cnblogs.com/wingcode/p/14527107.html
https://github.com/lettuce-io/lettuce-core/issues/2082 关键一篇issue
https://github.com/lettuce-io/lettuce-core/pull/2253
https://www.cnblogs.com/songjiyang/p/16809694.html
https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/
https://pracucci.com/linux-tcp-rto-min-max-and-tcp-retries2.html

https://help.aliyun.com/document_detail/43848.html

https://www.cnkirito.moe/redis-connect/ 质量很高

**Comment by freeleeq** [comment]
mark

**Comment by quan7u** [comment]
@LeeqGe 已更新 😄

**Comment by freeleeq** [comment]
[自动回复] 邮件我已收到！
 
                       ——葛立青

**Comment by 3Flos** [comment]
mark

**Comment by yunbozhang-msft** [comment]
mark

**Comment by accjiyun** [comment]
@LeeqGe 葛老板生产环境`TCP_USER_TIMEOUT`设置的多少秒？我当前使用的 https://github.com/lettuce-io/lettuce-core/issues/2082#issuecomment-1702782618 demo里的30s

**Comment by freeleeq** [comment]
[自动回复] 邮件我已收到！
 
                       ——葛立青

**Comment by MoozeeJiao** [comment]
“可能是waf机制长连接清理” 这个场景是不是 tcpKeepAlive 解决，将方案一的ping换成每个tcp连接自己保活

**Comment by freeleeq** [comment]
[自动回复] 邮件我已收到！
 
                       ——葛立青
